config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    namespace :api, defaults: { format: 'json' } do
      resources :rental_items, only: [:update]
    end

    namespace :admin do
      get '/csv_imports', controller: :csv_imports, action: :index, as: :csv_import_index
      post '/csv_imports/template', controller: :csv_imports, action: :template, as: :csv_import_template, defaults: { format: 'csv' }
      post '/csv_imports/import', controller: :csv_imports, action: :import, as: :csv_import_import, defaults: { format: 'html' }

      resources :recurrings, except: :show do
        resources :plans, except: :show
      end

      resources :rental_items do
        member do
          put :ship
          put :return
          put :purchase
          get :export
        end
      end

      resources :taxons_descriptions, except: :show

      resources :subscriptions, only: :index
      resources :subscription_events, only: :index
    end

    resources :recurring_hooks, only: :none do
      post :handler, on: :collection
    end

    resources :subscriptions, only: [:index, :create, :destroy, :new]

    get '/subscriptions/step1' => 'subscriptions#step1', :as => :subscriptions_step1
    get '/subscriptions/step2' => 'subscriptions#step2', :as => :subscriptions_step2
    get '/subscriptions/registration' => 'subscriptions#registration', :as => :subscriptions_registration
    put '/subscriptions/registration' => 'subscriptions#update_registration', :as => :update_subscriptions_registration

    resources :rental_items

    post 'rental_items/cancel' => 'rental_items#cancel', :as => :rental_item_cancel

    #Filter Products
    #get '/products' => 'products#index'
    #get '/products/:name' => 'products#index'
    #get '/products/:brand_name/:item_name' => 'products#index'


    get 'brands' => 'brands#index', :as => :brands
    #get 'brands/:id' => 'brands#show', :as => :brand
    get 'brands/:id' => 'products#index', :as => :brand
    get 'brands/:brand_name/:item_name' => 'products#index'
    get 'brands/:id/*sub_id' => 'brands#show_with_category', :as => :brand_with_category
    #get 'category/:id' => 'category#show', :as => :category
    get 'category/:id' => 'products#index', :as => :category
    put 'users/add_to_favorite/:variant_id' => 'users#add_to_favorite', :as => :add_to_favorite_user

    # thanks
    get '/thankyou' => 'users#thankyou', :as => :thankyou
    get '/thanks_silver' => 'users#thanks_silver', :as => :thanks_silver
    get '/thanks_gold' => 'users#thanks_gold', :as => :thanks_gold
    get '/thanks_black' => 'users#thanks_black', :as => :thanks_black

    get 'account/billing' => 'users#billing', :as => :user_billing
    get 'account/history' => 'users#history', :as => :user_history
    get 'account/orders' => 'users#orders', :as => :user_orders
    get 'account/favorites' => 'users#favorites', :as => :user_favorites
    get 'account/setting' => 'users#setting', :as => :user_setting
    get 'account/unsubscribe' => 'users#unsubscribe', :as => :user_unsubscribe
    get 'account/edit/address' => 'users#edit_address', :as => :user_edit_address
    patch 'account/update_address' => 'users#update_address', :as => :user_update_address

    #checkout complete path
    get '/checkout/complete' => 'orders#complete', :as => :complete_order

    # pages
    get '/pages/qa' => 'pages#qa', :as => :pages_qa
    get '/pages/policy' => 'pages#policy', :as => :pages_policy
    get '/pages/termofuse' => 'pages#termofuse', :as => :pages_termofuse
    get '/pages/about' => 'pages#about', :as => :pages_about
    get '/pages/asct' => 'pages#asct', :as => :pages_asct
  end

  mount Spree::Core::Engine, :at => '/'

  #Error handling
  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/concerns/spree/plan/api_handler.rb
module Spree
  class Plan < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        #before_validation :set_api_plan_id, on: :create
        #after_create :create_plan
        #after_update :delete_plan, :if => [:deleted_at_changed?, :deleted_at?]
        #after_update :update_plan, :if => :name_changed?
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error: #{e.message}"
          errors.add :base, e.message
          false
        end
      end

      def provider
        recurring.present? ? recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private

      def set_api_plan_id
        #provider.set_api_plan_id(self)
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        extend ActiveSupport::Concern

        included do
          include SubscriptionApiHandler
          include SubscriptionEventApiHandler
        end

        def client
          @client ||= WebPay.new(preferred_secret_key)
        end

        def error_class
          WebPay::ApiError
        end

        def raise_invalid_object_error(object, type)
          raise error_class.new("Not a valid object.") unless object.is_a?(type)
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionApiHandler
          def subscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            customer_id = find_or_create_customer(subscription)

            recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                description: subscription.plan.name,
            )

            if recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            recursion
          end

          def change_subscription(subscription, old_subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            if subscription.amount > old_subscription.amount
              upgrade(subscription, old_subscription)
            else
              downgrade(subscription, old_subscription)
            end

          end

          def upgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)
            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            extra_charge = subscription.amount - old_subscription.amount
            client.charge.create(
                amount: extra_charge,
                currency: "jpy",
                customer: customer_id,
                description: "会員プラン変更料 #{old_subscription.plan.name}から#{subscription.plan.name}に変更"
            )

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion

          end

          def downgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)

            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion


          end

          def unsubscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)
            client.recursion.delete(id: subscription.gateway_recursion_id)
          end

          private

          def find_or_create_customer(subscription)
            if subscription.source.gateway_customer_profile_id.present?
              subscription.source.gateway_customer_profile_id
            else
              customer = client.customer.create(
                  email: subscription.user.email,
                  description: subscription.user.email,
                  card: subscription.source.gateway_payment_profile_id,
              )

              subscription.source.update_attributes!({
                                                         gateway_customer_profile_id: customer.id,
                                                         gateway_payment_profile_id: nil
                                                     })

              customer.id
            end
          end
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_event_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionEventApiHandler
          def retrieve_event(event_id)
            begin
              client.event.retrieve(event_id)
            rescue error_class => e
              logger.error "Webpay Event error: #{e.message}"
              errors.add :base, "Webpay Event error: #{e.message}"
              nil
            end
          end

          def client
             @client ||= WebPay.new(preferred_secret_key)
          end
        end
      end
    end
  end
end

app/models/concerns/spree/subscription/api_handler.rb
module Spree
  class Subscription < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        attr_accessor :card_token
        before_create :subscribe
        before_update :unsubscribe, :if => [:unsubscribed_at_changed?, :unsubscribed_at?]
      end

      def subscribe
          if user.subscriptions.undeleted.any?
              old_subscription = user.subscriptions.undeleted.first

              # subscribe new recursion
              recursion = provider.change_subscription(self, old_subscription)

              # unsubscribe recursion and delete subscription
              old_subscription.save_and_manage_api(unsubscribed_at: Time.current)
          else
            # subscribe new recursion
            recursion = provider.subscribe(self)
          end

          self.gateway_recursion_id = recursion.id
          self.subscribed_at = Time.current
      end

      def unsubscribe
        provider.unsubscribe(self)
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error while subscribing: #{e.message}"
          errors.add :base, "There was a problem with your credit card"
          false
        end
      end

      def provider
        plan.try(:recurring).present? ? plan.recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private
    end
  end
end

app/models/concerns/spree/subscription/role_subscriber.rb
module Spree
  class Subscription < ActiveRecord::Base
    module RoleSubscriber
      extend ActiveSupport::Concern

      included do
        before_create :add_role_subscriber, :unless => :unsubscribed_at?
        before_update :remove_role_subscriber, :if => :unsubscribed_at?
      end

      def add_role_subscriber
        if role = subscriber_role
          user.spree_roles << role
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      # TODO don't remove role subscriber when upgrade/downgrade
      def remove_role_subscriber
        if role = subscriber_role
          user.spree_roles.destroy(role)
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      private

      def subscriber_role
        Spree::Role.where(name: 'subscriber').first
      end
    end
  end
end

app/models/spree/ability.rb
# Implementation class for Cancan gem.  Instead of overriding this class, consider adding new permissions
# using the special +register_ability+ method which allows extensions to add their own abilities.
#
# See http://github.com/ryanb/cancan for more details on cancan.
require 'cancan'
module Spree
  class Ability
    include CanCan::Ability

    class_attribute :abilities
    self.abilities = Set.new

    # Allows us to go beyond the standard cancan initialize method which makes it difficult for engines to
    # modify the default +Ability+ of an application.  The +ability+ argument must be a class that includes
    # the +CanCan::Ability+ module.  The registered ability should behave properly as a stand-alone class
    # and therefore should be easy to test in isolation.
    def self.register_ability(ability)
      self.abilities.add(ability)
    end

    def self.remove_ability(ability)
      self.abilities.delete(ability)
    end

    def initialize(user)
      self.clear_aliased_actions

      # override cancan default aliasing (we don't want to differentiate between read and index)
      alias_action :delete, to: :destroy
      alias_action :edit, to: :update
      alias_action :new, to: :create
      alias_action :new_action, to: :create
      alias_action :show, to: :read
      alias_action :index, :read, to: :display


      user ||= Spree.user_class.new

      if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
        can :manage, :all
      else
        can :display, Country
        can :display, OptionType
        can :display, OptionValue
        can :create, Order
        can [:read, :update], Order do |order, token|
          order.user == user || order.guest_token && token == order.guest_token
        end
        can :display, CreditCard, user_id: user.id
        can :display, Product
        can :display, ProductProperty
        can :display, Property
        can :create, Spree.user_class
        can [:read, :update, :destroy, :thankyou, :add_to_favorite], Spree.user_class, id: user.id
        can :display, State
        can :display, Taxon
        can :display, Taxonomy
        can :display, Variant
        can :display, Zone
      end

      # Include any abilities registered by extensions, etc.
      Ability.abilities.each do |clazz|
        ability = clazz.send(:new, user)
        @rules = rules + ability.send(:rules)
      end
    end
  end
end

app/models/spree/credit_card_decorator.rb
Spree::CreditCard.class_eval do
  belongs_to :recurring, :class_name => 'Spree::Recurring'
  has_many :subscriptions, as: :source
end

app/models/spree/favorite.rb
module Spree
  class Favorite < ActiveRecord::Base
    belongs_to :user
    belongs_to :variant, :counter_cache => :favorites_count

    def variant
      Spree::Variant.unscoped { super }
    end

    def user
      Spree::User.unscoped { super }
    end

  end
end

app/models/spree/image_decorator.rb
module Spree
  Image.class_eval do
    #before_validation :parse_attachment_from_source
    attr_accessor :source

    attachment_definitions[:attachment][:styles] = {
        :mini => '80x80>', # thumbs under image
        :small => '160x160>', # images on category view
        :thumb => '240x240>', # images on category view
        :product => '400x400>', # full product image
        :large => '600x600>' # light box image
    }

    attachment_definitions[:attachment][:path] = Kashikari::Application.config.image_path
    attachment_definitions[:attachment][:default_url] = Kashikari::Application.config.default_url

    Spree::Image.attachment_definitions[:attachment][:convert_options] = { all: Kashikari::Application.config.paperclip_options }


    def parse_attachment_from_source
      if source.present?
        self.attachment = URI.parse(source)
      end
    end

  end
end

app/models/spree/payment_method/check_decorator.rb
module Spree
  PaymentMethod::Check.class_eval do
    def payment_profiles_supported?
      true
    end
  end
end

app/models/spree/plan_product.rb
module Spree
  class PlanProduct < ActiveRecord::Base
    belongs_to :plan
    belongs_to :product
  end
end

app/models/spree/plan_taxon.rb
module Spree
  class PlanTaxon < ActiveRecord::Base
    belongs_to :plan
    belongs_to :taxon
  end
end

app/views/spree/products/_sub_menu.html.erb
<style>
  .brand_ul{padding: 0px;}
  .click_<%= name %>{cursor:pointer;}
  .panel-<%= name %>{display: none;}
</style>
<script type="text/javascript">
  $(document).ready(function(){

    if($(".panel-<%= name %>").css('display') == 'block'){
      $("#plus-arrow-<%= name %>").removeClass("aroow-r");
      $("#plus-arrow-<%= name %>").addClass("aroow-b");
    }else{
      $("#plus-arrow-<%= name %>").removeClass("aroow-b");
      $("#plus-arrow-<%= name %>").addClass("aroow-r");
    }

    $(".click_<%= name %>").click(function(){
    if($(".panel-<%= name %>").css('display') == 'none'){
      $("#plus-arrow-<%= name %>").removeClass("aroow-r");
      $("#plus-arrow-<%= name %>").addClass("aroow-b");
    }else{
      $("#plus-arrow-<%= name %>").removeClass("aroow-b");
      $("#plus-arrow-<%= name %>").addClass("aroow-r");
    }
    $(".panel-<%= name %>").slideToggle("slow");
  });
  });
</script>
<%
flag = true
if !brands.empty?
  if !params_brand.nil?
    arr_names = params_brand.split(',')
     brands.each { |i|
     if arr_names.include?("#{i.permalink}")
        flag = false
     end
    }
  end
end
 %>
 <div class="brand-prefix">
  <div class="click_<%= name %>">
    <span class="pc-h3"><%= label %> <span  id="plus-arrow-<%= name %>"></span>
  </div>
  <div class="panel-<%= name %>" style="<% if !flag %><%= 'display: block;' %><% else %> <%= 'display: none;' %> <% end %>">
    <ul class="ul">
      <% if !brands.empty?
        if !params_brand.nil?
          arr_names = params_brand.split(',')
          brands.each { |i| %>
          <li class="list">
            <% if arr_names.include?("#{i.permalink}") %>
            <%= check_box_tag 'brand', i.permalink, true, class: 'check', id: 'brand_' +"#{i.id}" %>
            <% else %>
            <%= check_box_tag 'brand', i.permalink, false, class: 'check', id: 'brand_' +"#{i.id}" %>
            <% end %>
            <label for="brand_<%= i.id %>" class="list_filter"><span class="check"></span><%= i.name %></label>
            <% if h[i.name] != 0 %>
            <label for="brand_<%= i.id %>" class="number_filter list_filter"><span class="check"></span> (<%= h[i.name] %>)</label>
            <% end %>
          </li>
          <% } %>
          <%= hidden_field_tag 'brand', params_brand, class: 'brand_hiden' %>
          <% else %>
          <% brands.each { |i| %>
          <li class="list">
            <%= check_box_tag 'brand', i.permalink, false, class: 'check', id: 'brand_' +"#{i.id}" %>
            <label for="brand_<%= i.id %>" class="list_filter"><span class="check"></span><%= i.name %></label>
            <% if h[i.name] != 0 %>
            <label for="brand_<%= i.id %>" class="number_filter list_filter"><span class="check"></span> (<%= h[i.name] %>)</label>
            <% end %>
          </li>
          <% } %>
          <%= hidden_field_tag 'brand', nil, class: 'brand_hiden' %>
          <%
        end
        else %>
        <%= hidden_field_tag 'brand', nil, class: 'brand_hiden' %>
        <%
        end %>
      </ul>
    </div>
  </div>

app/views/spree/products/show.html.erb
<% brand_name = @product.brands.first.name if @product.brands.present? %>
<% item_name = @product.items.first.name if @product.items.present? %>
<% color_names = @product.colors.map { |t| t.name }.join(",").to_s.concat(",") if @product.colors.present? %>
<% design_names = @product.designs.map { |t| t.name }.join(",").to_s.concat(",") if @product.designs.present? %>
<% size_names = @product.sizes.map { |t| t.name }.join(",").to_s.concat(",") if @product.sizes.present? %>
<% material_names = @product.materials.map { |t| t.name }.join(",").to_s if @product.materials.present? %>

<% content_for :title, head_title("#{brand_name}の#{item_name}(#{color_names}#{design_names}#{size_names}#{material_names})| ブランドネクタイ通販・レンタル KASHI KARI") %>
<% content_for :meta, meta_tags("#{brand_name},#{item_name},#{color_names}#{design_names}#{size_names}#{material_names},レンタル,メンズファッション,ブランド,通販,コーディネート,着こなし,KASHI KARI",
                                "#{brand_name}の#{item_name}(#{color_names}#{design_names}#{size_names}#{material_names})です| ブランドネクタイを通販やレンタル出来るKASHI KARI。タイピンやカフス、ジレなどが月額3600円から借り放題になるレンタルサービスです。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。") %>


<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><%= link_to 'メンズファッションレンタル KASHI KARI TOP', root_path %></li>
      <li><%= link_to "メンズファッション一覧", products_path %></li>
      <li>アイテム詳細</li>
    </ul>
  </div>
</nav>

<div class="product">
<div class="container">
<div class="product_detail">
<div class="detail_images">
  <div class="detail_thumb">
    <ul class="thumb_bxslider ul">

      <% if (@product.images + @product.variant_images).uniq.size > 0 %>

          <% @product.images.each do |image| %>
              <% if image.attachment_file_name.include?("-code") %>
                  <% @code_image = image %>
              <% else %>
                  <li>
                    <%= image_tag(image.attachment.url(:original)) %>
                  </li>
              <% end %>
          <% end %>

          <% if @product.taxons.pluck(:parent_id).include?(1) && @code_image.present? %>
              <% for i in 1..32 %>
                  <li>
                    <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/item.kashi-kari.jp/coordinate/#{sprintf("%02d", i)}/2.png", :class => 'front' %>
                    <%= image_tag @code_image.attachment.url(:original), :class => 'middle' %>
                    <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/item.kashi-kari.jp/coordinate/#{sprintf("%02d", i)}/1.jpg", :class => 'base' %>
                  </li>
              <% end %>
          <% end %>

      <% end %>

    </ul>
    <div class="thumb_bxpager">

      <% counter = -1 %>
      <% if (@product.images + @product.variant_images).uniq.size > 0 %>
          <% @product.images.each_with_index do |image, i| %>
              <% if !image.attachment_file_name.include?("-code") %>
                  <a data-slide-index="<%= counter + 1 %>" href="">
                    <%= image_tag(image.attachment.url(:original)) %>
                  </a>
                  <% counter = counter + 1 %>
              <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
  <% if (@product.images + @product.variant_images).uniq.size > 0 %>
      <% if @product.taxons.pluck(:parent_id).include?(1) && @code_image.present? %>
          <div class="viewOtherCordinate">
            <h3>コーディネートを見る</h3>

            <div class="pager_container">
              <div class="pager_bxslider">

                <div class="">
                  <div class="thumb_bxpager">
                    <% for i in 1..32 %>
                        <a data-slide-index="<%= counter + i %>" href="">
                          <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/item.kashi-kari.jp/coordinate/#{sprintf("%02d", i)}/2.png", :class => 'front' %>
                          <%= image_tag @code_image.attachment.url(:original), :class => 'middle' %>
                          <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/item.kashi-kari.jp/coordinate/#{sprintf("%02d", i)}/1.jpg", :class => 'base' %>
                        </a>
                        <% if i%8 == 0 && i != 32 %>
                            </div></div>
                            <div>
                              <div class="thumb_bxpager">
                        <% end %>
                    <% end %>
                    </div>
                   </div>
                </div>
            </div>
          </div>
      <% end %>
  <% end %>


  <% if @rent_items.present? %>
      <div class="past_rentals">
        <h3>過去に借りたアイテム</h3>
        <ul class="past_bxslider ul">

          <% @rent_items.each do |rent_items| %>
              <li>
                <%= link_to original_image(rent_items), product_path(rent_items) %>
              </li>
          <% end %>

        </ul>
      </div>
  <% end %>

  <div class="referal_items">

    <h3>関連アイテム</h3>
    <ul class="ul">
      <% @related_items.each do |related_item| %>
          <% if related_item != @product %>
              <li>
              <%= link_to original_image(related_item), product_path(related_item) %>
              <h4>
                <% if related_item.brands.present? %>
                    <%= related_item.brands.first.name %>
                <% end %>
              </h4>
              <% if spree_current_user %>
                  <% if spree_current_user.liked?(related_item.master) %>
                      <%= link_to "追加しました！", add_to_favorite_user_path(related_item.master), class: 'vote liked', method: :put, remote: true, data: {toggle_text: 'お気に入りに追加', toggle_href: add_to_favorite_user_path(related_item.master), id: related_item.master.id} %>
                  <% else %>
                      <%= link_to "お気に入りに追加", add_to_favorite_user_path(related_item.master), class: 'vote', method: :put, remote: true, data: {toggle_text: '追加しました！', toggle_href: add_to_favorite_user_path(related_item.master), id: related_item.master.id} %>
                  <% end %>
              <% else %>
                  <%= link_to "お気に入りに追加", signup_path, :class => 'signinToLike', :id => related_item.master.id
                    %>
              <% end %>
              </li>
          <% end  %>
      <% end %>
    </ul>
    <div class="cord_controll">
      <span class="left"></span>
      <span class="right"></span>
    </div>
  </div>
</div>
<div class="detail_info">
  <div class="info_meta">
    <ul class="ul">
      <li>
        <label>ブランド名：</label>
          <span>
            <% if @product.brands.present? %>
            <% brand = @product.brands.first %>
                <%= link_to brand.name, brand_path(brand) %>
            <% else %>
            -
            <% end %>
          </span>
      </li>
      <li>
        <label>アイテム：</label>
              <span>
                <% if @product.items.present? %>
                <% item = @product.items.first %>
                    <%= link_to item.name, category_path(item) %>
                <% else %>
                -
                <% end %>
              </span>
      </li>
      <li>
        <label>色：</label>
              <span>
                <% if @product.colors.present? %>
                <% @product.colors.each do |color| %>
                    <%= link_to color.name, products_path(:color_id => color.id) %>
                <% end %>
                <% else %>
                -
                <% end %>
              </span>
      </li>
      <li>
        <label>柄：</label>
              <span>
                <% if @product.designs.present? %>
                <% @product.designs.each do |design| %>
                    <%= link_to design.name, products_path(:design_id => design.id) %>
                <% end %>
                <% else %>
                -
                <% end %>
              </span>
      </li>
      <li>
        <label>素材：</label>
              <span>
                <% if @product.materials.present? %>
                <% @product.materials.each do |material| %>
                    <%= link_to material.name, products_path(:material_id => material.id) %>
                <% end %>
                <% else %>
                -
                <% end %>
              </span>
      </li>
      <% if @product.sizes.present? %>
          <li>
            <label>剣先サイズ：</label>
              <span>
                <% @product.sizes.each do |size| %>
                    <%= link_to size.name, products_path(:size_id => size.id) %>
                <% end %>
              </span>
          </li>
      <% end %>
      <li>
        <label>サイズ：</label>
              <span>
                <% if @product.size.present? %>
                <%= simple_format @product.size %>
                <% else %>
                -
                <% end %>
              </span>
      </li>

      <li>
        <label>お気に入り登録数：</label>
        <span><%= @product.total_favorite %></span>
      </li>
      <li>
        <label>価格：</label>
        <span><%= display_price(@product) %>(税込)</span>
      </li>
      <li>
        <label>累計ビュー：</label>
        <span><%= @product.impressions_count %>pv</span>
      </li>
    </ul>
  </div>

  <div class="info_buttons">
    <% if @product.total_on_hand < 1 %>
        <div class="outOfStock">
          販売済み
        </div>
    <% elsif @product.total_on_hand <= @product.master.rental_qty %>
        <div class="rentaled">
          <%= image_tag 'products/not_available.png', :alt => 'Not Available' %>
        </div>
    <% end %>

    <% if spree_current_user %>
        <% if spree_current_user.liked?(@product.master) %>
            <%= link_to "追加しました！", add_to_favorite_user_path(@product.master), class: 'vote liked', method: :put, remote: true, data: {toggle_text: 'お気に入りに追加', toggle_href: add_to_favorite_user_path(@product.master), id: @product.master.id} %>
        <% else %>
            <%= link_to "お気に入りに追加", add_to_favorite_user_path(@product.master), class: 'vote', method: :put, remote: true, data: {toggle_text: '追加しました！', toggle_href: add_to_favorite_user_path(@product.master), id: @product.master.id} %>
        <% end %>
    <% else %>
        <%= link_to "お気に入りに追加", signup_path, :class => 'signinToLike', :id => @product.master.id %>
    <% end %>
    <p>
      お気に入りに追加したアイテムはマイページよりレンタル手続きが行えます。
    </p>
    <% if spree_current_user %>
        <%= link_to account_path, :class => 'info_mypage_link' do %>
            <p>マイページへ <i class="fa fa-angle-double-right"></i></p>
        <% end %>
    <% end %>

  </div>
  <% if @product.description.present? %>
      <div class="info_itemDetail">
        <h3>アイテム詳細</h3>
        <%= simple_format @product.description %>
      </div>
  <% end %>
</div>
</div>
</div>
</div>
<script type="text/javascript">
  $(".signinToLike").click(function(){
    sessionStorage.setItem('product_id', $(this).attr('id'));
  });
</script>