config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    namespace :api, defaults: { format: 'json' } do
      resources :rental_items, only: [:update]
    end

    namespace :admin do
      get '/csv_imports', controller: :csv_imports, action: :index, as: :csv_import_index
      post '/csv_imports/template', controller: :csv_imports, action: :template, as: :csv_import_template, defaults: { format: 'csv' }
      post '/csv_imports/import', controller: :csv_imports, action: :import, as: :csv_import_import, defaults: { format: 'html' }

      resources :recurrings, except: :show do
        resources :plans, except: :show
      end

      resources :rental_items do
        member do
          put :ship
          put :return
          put :purchase
          get :export
        end
      end

      resources :taxons_descriptions, except: :show

      resources :subscriptions, only: :index
      resources :subscription_events, only: :index
    end

    resources :recurring_hooks, only: :none do
      post :handler, on: :collection
    end

    resources :subscriptions, only: [:index, :create, :destroy, :new]

    get '/subscriptions/step1' => 'subscriptions#step1', :as => :subscriptions_step1
    get '/subscriptions/step2' => 'subscriptions#step2', :as => :subscriptions_step2
    get '/subscriptions/registration' => 'subscriptions#registration', :as => :subscriptions_registration
    put '/subscriptions/registration' => 'subscriptions#update_registration', :as => :update_subscriptions_registration

    resources :rental_items

    post 'rental_items/cancel' => 'rental_items#cancel', :as => :rental_item_cancel

    #Filter Products
    #get '/products' => 'products#index'
    #get '/products/:name' => 'products#index'
    #get '/products/:brand_name/:item_name' => 'products#index'


    get 'brands' => 'brands#index', :as => :brands
    #get 'brands/:id' => 'brands#show', :as => :brand
    get 'brands/:id' => 'products#index', :as => :brand
    get 'brands/:brand_name/:item_name' => 'products#index'
    get 'brands/:id/*sub_id' => 'brands#show_with_category', :as => :brand_with_category
    #get 'category/:id' => 'category#show', :as => :category
    get 'category/:id' => 'products#index', :as => :category
    put 'users/add_to_favorite/:variant_id' => 'users#add_to_favorite', :as => :add_to_favorite_user

    # thanks
    get '/thankyou' => 'users#thankyou', :as => :thankyou
    get '/thanks_silver' => 'users#thanks_silver', :as => :thanks_silver
    get '/thanks_gold' => 'users#thanks_gold', :as => :thanks_gold
    get '/thanks_black' => 'users#thanks_black', :as => :thanks_black

    get 'account/billing' => 'users#billing', :as => :user_billing
    get 'account/history' => 'users#history', :as => :user_history
    get 'account/orders' => 'users#orders', :as => :user_orders
    get 'account/favorites' => 'users#favorites', :as => :user_favorites
    get 'account/setting' => 'users#setting', :as => :user_setting
    get 'account/unsubscribe' => 'users#unsubscribe', :as => :user_unsubscribe
    get 'account/edit/address' => 'users#edit_address', :as => :user_edit_address
    patch 'account/update_address' => 'users#update_address', :as => :user_update_address

    #checkout complete path
    get '/checkout/complete' => 'orders#complete', :as => :complete_order

    # pages
    get '/pages/qa' => 'pages#qa', :as => :pages_qa
    get '/pages/policy' => 'pages#policy', :as => :pages_policy
    get '/pages/termofuse' => 'pages#termofuse', :as => :pages_termofuse
    get '/pages/about' => 'pages#about', :as => :pages_about
    get '/pages/asct' => 'pages#asct', :as => :pages_asct
  end

  mount Spree::Core::Engine, :at => '/'

  #Error handling
  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/concerns/spree/recurring/webpay_recurring/api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        extend ActiveSupport::Concern

        included do
          include SubscriptionApiHandler
          include SubscriptionEventApiHandler
        end

        def client
          @client ||= WebPay.new(preferred_secret_key)
        end

        def error_class
          WebPay::ApiError
        end

        def raise_invalid_object_error(object, type)
          raise error_class.new("Not a valid object.") unless object.is_a?(type)
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionApiHandler
          def subscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            customer_id = find_or_create_customer(subscription)

            recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                description: subscription.plan.name,
            )

            if recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            recursion
          end

          def change_subscription(subscription, old_subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            if subscription.amount > old_subscription.amount
              upgrade(subscription, old_subscription)
            else
              downgrade(subscription, old_subscription)
            end

          end

          def upgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)
            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            extra_charge = subscription.amount - old_subscription.amount
            client.charge.create(
                amount: extra_charge,
                currency: "jpy",
                customer: customer_id,
                description: "会員プラン変更料 #{old_subscription.plan.name}から#{subscription.plan.name}に変更"
            )

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion

          end

          def downgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)

            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion


          end

          def unsubscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)
            client.recursion.delete(id: subscription.gateway_recursion_id)
          end

          private

          def find_or_create_customer(subscription)
            if subscription.source.gateway_customer_profile_id.present?
              subscription.source.gateway_customer_profile_id
            else
              customer = client.customer.create(
                  email: subscription.user.email,
                  description: subscription.user.email,
                  card: subscription.source.gateway_payment_profile_id,
              )

              subscription.source.update_attributes!({
                                                         gateway_customer_profile_id: customer.id,
                                                         gateway_payment_profile_id: nil
                                                     })

              customer.id
            end
          end
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_event_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionEventApiHandler
          def retrieve_event(event_id)
            begin
              client.event.retrieve(event_id)
            rescue error_class => e
              logger.error "Webpay Event error: #{e.message}"
              errors.add :base, "Webpay Event error: #{e.message}"
              nil
            end
          end

          def client
             @client ||= WebPay.new(preferred_secret_key)
          end
        end
      end
    end
  end
end

app/models/spree/recurring.rb
module Spree
  class Recurring < Spree::Base
    include RestrictiveDestroyer

    acts_as_restrictive_destroyer

    preference :secret_key, :string
    preference :public_key, :string

    has_many :plans
    has_many :credit_cards, class_name: "Spree::CreditCard"

    attr_readonly :type
    validates :type, :name, presence: true
    validates :type, uniqueness: { message: 'of provider recurring already exists' }

    scope :active, -> { undeleted.where(active: true) }

    def self.display_name
      name.gsub(%r{.+:}, '')
    end

    def visible?
      active? && !is_destroyed?
    end

    def default_plan
      plans.default
    end

    def has_preferred_keys?
      preferred_secret_key.present? && preferred_public_key.present?
    end
  end
end

app/models/spree/recurring/webpay_recurring.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Recurring
      include ApiHandler

      #WEBHOOKS = ['recursion.succeeded', 'recursion.failed', 'recursion.created', 'recursion.resumed', 'recursion.deleted', 'charge.succeeded', 'charge.failed', 'charge.refunded', 'charge.captured', 'customer.created', 'customer.updated', 'customer.deleted']
      WEBHOOKS = ['recursion.succeeded', 'recursion.failed', 'charge.succeeded', 'charge.failed']


      INTERVAL = { month: 'Monthly', year: 'Annually' }
      CURRENCY = { usd: 'USD', gbp: 'GBP', jpy: 'JPY', eur: 'EUR', aud: 'AUD', hkd: 'HKD', sek: 'SEK', nok: 'NOK', dkk: 'DKK', pen: 'PEN', cad: 'CAD'}

      def payment_source_class
        CreditCard
      end
    end
  end
end

app/controllers/spree/admin/recurrings_controller.rb
module Spree
  module Admin
    class RecurringsController < Spree::Admin::BaseController
      before_action :find_recurring, :only => [:edit, :update, :destroy]
      before_action :build_recurring, :only => :create

      def index
        @recurrings = Spree::Recurring.undeleted.order('id desc')
      end

      def new
        @recurring = Spree::Recurring.new
      end

      def create
        if @recurring.save
          flash[:notice] = "Recurring created succesfully."
          redirect_to edit_admin_recurring_url(@recurring)
        else
          render :new
        end
      end

      def update
        if @recurring.update_attributes(recurring_params(:update))
          flash[:notice] = "Recurring updated succesfully."
          redirect_to edit_admin_recurring_url(@recurring)
        else
          render :edit
        end
      end

      def destroy
        @recurring.restrictive_destroy
      end

      private

      def find_recurring
        unless @recurring = Spree::Recurring.undeleted.where(id: params[:id]).first
          flash[:error] = "Recurring not found."
          respond_to do |format|
            format.html {redirect_to admin_recurrings_url}
            format.js { }
          end
        end
      end

      def recurring_params(action=:create)
        if action == :create
          params.require(:recurring).permit(:name, :type, :description, :active)
        else
          params.require(:recurring).permit(:name, :description, :active).merge(preference_params)
        end
      end

      def build_recurring
        @recurring = recurring_params.delete(:type).constantize.new(recurring_params)
      end

      def preference_params
        params[ActiveModel::Naming.param_key(@recurring)]
      end
    end
  end
end

app/views/spree/admin/recurrings/_form.html.erb
<div data-hook="admin_recurring_form_fields">

  <div data-hook="recurring">

    <div class="alpha four columns">
      <div id="preference-settings" data-hook class="field">
        <%= label_tag nil, Spree.t(:provider) %>
        <%= select(:recurring, :type, Rails.application.config.spree.recurring_providers.collect {|pro| [pro.display_name, pro]}, {}, {disabled: !@recurring.new_record?, class: 'select2 fullwidth'}) %>

        <% unless @recurring.new_record? %>
          <%= preference_fields(@recurring, f) %>

          <% if @recurring.respond_to?(:preferences) %>
            <div id="gateway-settings-warning" class="info warning"><%= Spree.t(:provider_settings_warning) %></div>
          <% end %>
        <% end %>
      </div>      
      <div data-hook="active" class="field">
        <ul>
          <li>
            <%= label_tag :nil, Spree.t(:active) %>
            <%= check_box :recurring, :active %>
          </li>
        </ul>
      </div>
    </div>
    
    <div class="omega eight columns">
      <div data-hook="name" class="field">
        <%= label_tag nil, Spree.t(:name) %>
        <%= text_field :recurring, :name, :class => 'fullwidth' %>
      </div>
      <div data-hook="description" class="field">
        <%= label_tag nil, Spree.t(:description) %>
        <%= text_area :recurring, :description, {:cols => 60, :rows => 6, :class => 'fullwidth'} %>
      </div>  
    </div>
    
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/recurrings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_recurring) %> <i class="icon-arrow-right"></i> <%= @recurring.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_recurrings_list), spree.admin_recurrings_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @recurring } %>

<%= form_for @recurring, :url => admin_recurring_path(@recurring) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <% if @recurring.has_preferred_keys? %>
        <%= button_link_to Spree.t(:manage_plans), admin_recurring_plans_url(@recurring) %>
      <% end %>
      <%= button Spree.t('actions.update'), 'icon-refresh' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/recurrings/index.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:recurring) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_recurring), new_admin_recurring_url, :icon => 'icon-plus', :id => 'admin_new_recurring_link' %>
  </li>
<% end %>

<% if @recurrings.any? %>
  <table class="index" id='listing_recurrings'>
    <colgroup>
      <col style="width: 30%">
      <col style="width: 25%">
      <col style="width: 25%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="admin_payment_methods_index_headers">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:provider) %></th>
        <th><%= Spree.t(:active) %></th>
        <th data-hook="admin_payment_methods_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @recurrings.each do |recurring|%>
        <tr id="<%= spree_dom_id recurring %>" data-hook="admin_recurrings_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= recurring.name %></td>
          <td class="align-center"><%= recurring.class.display_name %></td>
          <td class="align-center"><%= recurring.active ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td data-hook="admin_recurrings_index_row_actions" class="actions">
            <%= link_to_edit_url edit_admin_recurring_url(recurring), :no_text => true %>
            <%= link_to_delete recurring, url: admin_recurring_url(recurring), :no_text => true  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/recurring')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_recurring_url %>!
  </div>
<% end %>

app/views/spree/admin/recurrings/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_recurring) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_recurrings_list), admin_recurrings_url, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @recurring } %>

<%= form_for @recurring, :url => admin_recurrings_url do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t(:create), 'icon-ok' %>
    </div>
  </fieldset>
<% end %>