config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    namespace :api, defaults: { format: 'json' } do
      resources :rental_items, only: [:update]
    end

    namespace :admin do
      get '/csv_imports', controller: :csv_imports, action: :index, as: :csv_import_index
      post '/csv_imports/template', controller: :csv_imports, action: :template, as: :csv_import_template, defaults: { format: 'csv' }
      post '/csv_imports/import', controller: :csv_imports, action: :import, as: :csv_import_import, defaults: { format: 'html' }

      resources :recurrings, except: :show do
        resources :plans, except: :show
      end

      resources :rental_items do
        member do
          put :ship
          put :return
          put :purchase
          get :export
        end
      end

      resources :taxons_descriptions, except: :show

      resources :subscriptions, only: :index
      resources :subscription_events, only: :index
    end

    resources :recurring_hooks, only: :none do
      post :handler, on: :collection
    end

    resources :subscriptions, only: [:index, :create, :destroy, :new]

    get '/subscriptions/step1' => 'subscriptions#step1', :as => :subscriptions_step1
    get '/subscriptions/step2' => 'subscriptions#step2', :as => :subscriptions_step2
    get '/subscriptions/registration' => 'subscriptions#registration', :as => :subscriptions_registration
    put '/subscriptions/registration' => 'subscriptions#update_registration', :as => :update_subscriptions_registration

    resources :rental_items

    post 'rental_items/cancel' => 'rental_items#cancel', :as => :rental_item_cancel

    #Filter Products
    #get '/products' => 'products#index'
    #get '/products/:name' => 'products#index'
    #get '/products/:brand_name/:item_name' => 'products#index'


    get 'brands' => 'brands#index', :as => :brands
    #get 'brands/:id' => 'brands#show', :as => :brand
    get 'brands/:id' => 'products#index', :as => :brand
    get 'brands/:brand_name/:item_name' => 'products#index'
    get 'brands/:id/*sub_id' => 'brands#show_with_category', :as => :brand_with_category
    #get 'category/:id' => 'category#show', :as => :category
    get 'category/:id' => 'products#index', :as => :category
    put 'users/add_to_favorite/:variant_id' => 'users#add_to_favorite', :as => :add_to_favorite_user

    # thanks
    get '/thankyou' => 'users#thankyou', :as => :thankyou
    get '/thanks_silver' => 'users#thanks_silver', :as => :thanks_silver
    get '/thanks_gold' => 'users#thanks_gold', :as => :thanks_gold
    get '/thanks_black' => 'users#thanks_black', :as => :thanks_black

    get 'account/billing' => 'users#billing', :as => :user_billing
    get 'account/history' => 'users#history', :as => :user_history
    get 'account/orders' => 'users#orders', :as => :user_orders
    get 'account/favorites' => 'users#favorites', :as => :user_favorites
    get 'account/setting' => 'users#setting', :as => :user_setting
    get 'account/unsubscribe' => 'users#unsubscribe', :as => :user_unsubscribe
    get 'account/edit/address' => 'users#edit_address', :as => :user_edit_address
    patch 'account/update_address' => 'users#update_address', :as => :user_update_address

    #checkout complete path
    get '/checkout/complete' => 'orders#complete', :as => :complete_order

    # pages
    get '/pages/qa' => 'pages#qa', :as => :pages_qa
    get '/pages/policy' => 'pages#policy', :as => :pages_policy
    get '/pages/termofuse' => 'pages#termofuse', :as => :pages_termofuse
    get '/pages/about' => 'pages#about', :as => :pages_about
    get '/pages/asct' => 'pages#asct', :as => :pages_asct
  end

  mount Spree::Core::Engine, :at => '/'

  #Error handling
  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/concerns/spree/plan/api_handler.rb
module Spree
  class Plan < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        #before_validation :set_api_plan_id, on: :create
        #after_create :create_plan
        #after_update :delete_plan, :if => [:deleted_at_changed?, :deleted_at?]
        #after_update :update_plan, :if => :name_changed?
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error: #{e.message}"
          errors.add :base, e.message
          false
        end
      end

      def provider
        recurring.present? ? recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private

      def set_api_plan_id
        #provider.set_api_plan_id(self)
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        extend ActiveSupport::Concern

        included do
          include SubscriptionApiHandler
          include SubscriptionEventApiHandler
        end

        def client
          @client ||= WebPay.new(preferred_secret_key)
        end

        def error_class
          WebPay::ApiError
        end

        def raise_invalid_object_error(object, type)
          raise error_class.new("Not a valid object.") unless object.is_a?(type)
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionApiHandler
          def subscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            customer_id = find_or_create_customer(subscription)

            recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                description: subscription.plan.name,
            )

            if recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            recursion
          end

          def change_subscription(subscription, old_subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            if subscription.amount > old_subscription.amount
              upgrade(subscription, old_subscription)
            else
              downgrade(subscription, old_subscription)
            end

          end

          def upgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)
            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            extra_charge = subscription.amount - old_subscription.amount
            client.charge.create(
                amount: extra_charge,
                currency: "jpy",
                customer: customer_id,
                description: "会員プラン変更料 #{old_subscription.plan.name}から#{subscription.plan.name}に変更"
            )

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion

          end

          def downgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)

            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion


          end

          def unsubscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)
            client.recursion.delete(id: subscription.gateway_recursion_id)
          end

          private

          def find_or_create_customer(subscription)
            if subscription.source.gateway_customer_profile_id.present?
              subscription.source.gateway_customer_profile_id
            else
              customer = client.customer.create(
                  email: subscription.user.email,
                  description: subscription.user.email,
                  card: subscription.source.gateway_payment_profile_id,
              )

              subscription.source.update_attributes!({
                                                         gateway_customer_profile_id: customer.id,
                                                         gateway_payment_profile_id: nil
                                                     })

              customer.id
            end
          end
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_event_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionEventApiHandler
          def retrieve_event(event_id)
            begin
              client.event.retrieve(event_id)
            rescue error_class => e
              logger.error "Webpay Event error: #{e.message}"
              errors.add :base, "Webpay Event error: #{e.message}"
              nil
            end
          end

          def client
             @client ||= WebPay.new(preferred_secret_key)
          end
        end
      end
    end
  end
end

app/models/concerns/spree/subscription/api_handler.rb
module Spree
  class Subscription < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        attr_accessor :card_token
        before_create :subscribe
        before_update :unsubscribe, :if => [:unsubscribed_at_changed?, :unsubscribed_at?]
      end

      def subscribe
          if user.subscriptions.undeleted.any?
              old_subscription = user.subscriptions.undeleted.first

              # subscribe new recursion
              recursion = provider.change_subscription(self, old_subscription)

              # unsubscribe recursion and delete subscription
              old_subscription.save_and_manage_api(unsubscribed_at: Time.current)
          else
            # subscribe new recursion
            recursion = provider.subscribe(self)
          end

          self.gateway_recursion_id = recursion.id
          self.subscribed_at = Time.current
      end

      def unsubscribe
        provider.unsubscribe(self)
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error while subscribing: #{e.message}"
          errors.add :base, "There was a problem with your credit card"
          false
        end
      end

      def provider
        plan.try(:recurring).present? ? plan.recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private
    end
  end
end

app/models/concerns/spree/subscription/role_subscriber.rb
module Spree
  class Subscription < ActiveRecord::Base
    module RoleSubscriber
      extend ActiveSupport::Concern

      included do
        before_create :add_role_subscriber, :unless => :unsubscribed_at?
        before_update :remove_role_subscriber, :if => :unsubscribed_at?
      end

      def add_role_subscriber
        if role = subscriber_role
          user.spree_roles << role
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      # TODO don't remove role subscriber when upgrade/downgrade
      def remove_role_subscriber
        if role = subscriber_role
          user.spree_roles.destroy(role)
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      private

      def subscriber_role
        Spree::Role.where(name: 'subscriber').first
      end
    end
  end
end

app/models/spree/ability.rb
# Implementation class for Cancan gem.  Instead of overriding this class, consider adding new permissions
# using the special +register_ability+ method which allows extensions to add their own abilities.
#
# See http://github.com/ryanb/cancan for more details on cancan.
require 'cancan'
module Spree
  class Ability
    include CanCan::Ability

    class_attribute :abilities
    self.abilities = Set.new

    # Allows us to go beyond the standard cancan initialize method which makes it difficult for engines to
    # modify the default +Ability+ of an application.  The +ability+ argument must be a class that includes
    # the +CanCan::Ability+ module.  The registered ability should behave properly as a stand-alone class
    # and therefore should be easy to test in isolation.
    def self.register_ability(ability)
      self.abilities.add(ability)
    end

    def self.remove_ability(ability)
      self.abilities.delete(ability)
    end

    def initialize(user)
      self.clear_aliased_actions

      # override cancan default aliasing (we don't want to differentiate between read and index)
      alias_action :delete, to: :destroy
      alias_action :edit, to: :update
      alias_action :new, to: :create
      alias_action :new_action, to: :create
      alias_action :show, to: :read
      alias_action :index, :read, to: :display


      user ||= Spree.user_class.new

      if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
        can :manage, :all
      else
        can :display, Country
        can :display, OptionType
        can :display, OptionValue
        can :create, Order
        can [:read, :update], Order do |order, token|
          order.user == user || order.guest_token && token == order.guest_token
        end
        can :display, CreditCard, user_id: user.id
        can :display, Product
        can :display, ProductProperty
        can :display, Property
        can :create, Spree.user_class
        can [:read, :update, :destroy, :thankyou, :add_to_favorite], Spree.user_class, id: user.id
        can :display, State
        can :display, Taxon
        can :display, Taxonomy
        can :display, Variant
        can :display, Zone
      end

      # Include any abilities registered by extensions, etc.
      Ability.abilities.each do |clazz|
        ability = clazz.send(:new, user)
        @rules = rules + ability.send(:rules)
      end
    end
  end
end

app/models/spree/credit_card_decorator.rb
Spree::CreditCard.class_eval do
  belongs_to :recurring, :class_name => 'Spree::Recurring'
  has_many :subscriptions, as: :source
end

app/models/spree/favorite.rb
module Spree
  class Favorite < ActiveRecord::Base
    belongs_to :user
    belongs_to :variant, :counter_cache => :favorites_count

    def variant
      Spree::Variant.unscoped { super }
    end

    def user
      Spree::User.unscoped { super }
    end

  end
end

app/models/spree/image_decorator.rb
module Spree
  Image.class_eval do
    #before_validation :parse_attachment_from_source
    attr_accessor :source

    attachment_definitions[:attachment][:styles] = {
        :mini => '80x80>', # thumbs under image
        :small => '160x160>', # images on category view
        :thumb => '240x240>', # images on category view
        :product => '400x400>', # full product image
        :large => '600x600>' # light box image
    }

    attachment_definitions[:attachment][:path] = Kashikari::Application.config.image_path
    attachment_definitions[:attachment][:default_url] = Kashikari::Application.config.default_url

    Spree::Image.attachment_definitions[:attachment][:convert_options] = { all: Kashikari::Application.config.paperclip_options }


    def parse_attachment_from_source
      if source.present?
        self.attachment = URI.parse(source)
      end
    end

  end
end

app/models/spree/payment_method/check_decorator.rb
module Spree
  PaymentMethod::Check.class_eval do
    def payment_profiles_supported?
      true
    end
  end
end

app/models/spree/plan_product.rb
module Spree
  class PlanProduct < ActiveRecord::Base
    belongs_to :plan
    belongs_to :product
  end
end

app/models/spree/plan_taxon.rb
module Spree
  class PlanTaxon < ActiveRecord::Base
    belongs_to :plan
    belongs_to :taxon
  end
end

app/views/spree/users/edit_address.html.erb
<% content_for :title, head_title("配送情報 | 月額制メンズファッションレンタルKASHI KARI") %>
<% content_for :meta, meta_tags("配送情報,レンタル,メンズファッション,ブランド,コーディネート,着こなし,KASHI KARI",
                                "配送情報です。| KASHI KARIはメンズファッションアイテムが月額1980円から借り放題になるレンタルサービスです。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。") %>


<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><%= link_to 'メンズファッションレンタル KASHI KARI TOP', root_path %></li>
      <li><%= link_to "マイページ", account_path %></li>
      <li>配送情報</li>
    </ul>
  </div>
</nav>
<div class="edit_adddress">
  <div class="container">

    <%= form_for @user, url: user_update_address_url do |f| %>
      <div class="pre_title">
        <h1 class="f_fm">配送情報</h1>
      </div>
      <div class="container-form layout">
        <div class="input_row">
          <div class="split_2">
            <label for="">氏名（姓）</label>
            <%= text_field_tag "user[address_attributes][last_name]",@user.ship_address.lastname %>

          </div>
          <div class="split_2">
            <label for="">氏名（名）</label>
            <%= text_field_tag "user[address_attributes][first_name]",@user.ship_address.firstname %>
          </div>
        </div>
        <div class="input_row">
          <div class="split_2">
            <label for="">郵便番号</label>
            <%= text_field_tag "user[address_attributes][zipcode]",  @user.ship_address.zipcode, {placeholder: "例）1010001"} %>
          </div>
        </div>
        <div class="input_row">
          <div class="split_2">
            <label for="">都道府県</label>
            <%= text_field_tag "user[address_attributes][city]",  @user.ship_address.city %>
          </div>
          <div class="split_2">
            <label for="">市町村</label>
            <%= text_field_tag "user[address_attributes][address1]",  @user.ship_address.address1 %>
          </div>
        </div>
        <div class="input_row">
          <div class="">
            <label for="">以降の住所</label>
            <%= text_field_tag "user[address_attributes][address2]",  @user.ship_address.address2 %>
          </div>
        </div>
        <div class="input_row tel">
          <div class="split_03">
            <label for="">電話番号</label>
            <%= text_field_tag "user[address_attributes][phone]",  @user.ship_address.phone %>
          </div>
        </div>

        <div class="submit_buttom">
          <%= f.submit "編集", class: 'continue' %>
          <script>Spree.disableSaveOnClick();</script>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/users/edit_address_smart_phone.html.erb
<% content_for :title, head_title("配送情報 | 月額制メンズファッションレンタルKASHI KARI") %>
<% content_for :meta, meta_tags("配送情報,レンタル,メンズファッション,ブランド,コーディネート,着こなし,KASHI KARI",
                                "配送情報です。| KASHI KARIはメンズファッションアイテムが月額1980円から借り放題になるレンタルサービスです。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。") %>

<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><%= link_to 'メンズファッションレンタル KASHI KARI TOP', root_path %></li>
      <li><%= link_to "マイページ", account_path %></li>
      <li>配送情報</li>
    </ul>
  </div>
</nav>
<div class="editAddress_container layout">


  <%= form_for @user, url: user_update_address_url do |f| %>

    <div class="pre_title">
      <h1 class="f_fm">配送情報</h1>
    </div>
    <div class="payment_address">
      <div class="label-set">
        氏名（姓）
      </div>
      <div class="input-set">
        <%= text_field_tag "user[address_attributes][last_name]",@user.ship_address.lastname %>
      </div>
      <div class="label-set">
        氏名（名）
      </div>
      <div class="input-set">
        <%= text_field_tag "user[address_attributes][first_name]",@user.ship_address.firstname %>
      </div>
      <div class="label-set">
        郵便番号
      </div>
      <div class="input-set">
        <label for=""></label>
        <%= text_field_tag "user[address_attributes][zipcode]",  @user.ship_address.zipcode, {placeholder: "例）1010001"} %>
      </div>
      <div class="label-set">
        都道府県
      </div>
      <div class="input-set">
        <%= text_field_tag "user[address_attributes][city]",  @user.ship_address.city %>
      </div>
      <div class="label-set">
        市町村
      </div>
      <div class="input-set">
        <%= text_field_tag "user[address_attributes][address1]",  @user.ship_address.address1 %>
      </div>
      <div class="label-set">
        以降の住所
      </div>
      <div class="input-set">
        <%= text_field_tag "user[address_attributes][address2]",  @user.ship_address.address2 %>
      </div>
      <div class="label-set">
        電話番号
      </div>
      <div class="input-set">
        <%= text_field_tag "user[address_attributes][phone]",  @user.ship_address.phone %>
      </div>
    </div>

    <div class="submit_button">
      <%= f.submit "編集", class: 'button-block continue' %>
      <script>Spree.disableSaveOnClick();</script>
    </div>

  <% end %>
</div>

app/views/spree/users/history.html.erb
<% content_for :title, head_title("過去に借りたアイテム | 月額制メンズファッションレンタルKASHI KARI") %>
<% content_for :meta, meta_tags("過去に借りたアイテム,レンタル,メンズファッション,ブランド,コーディネート,着こなし,KASHI KARI",
                                "過去に借りたアイテムです。| KASHI KARIはメンズファッションアイテムが月額1980円から借り放題になるレンタルサービスです。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。") %>


<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><%= link_to 'メンズファッションレンタル KASHI KARI TOP', root_path %></li>
      <li><%= link_to "マイページ", account_path %></li>
      <li>過去に借りたアイテム</li>
    </ul>
  </div>
</nav>
<section id="user_summary" class="users-show">
  <div class="user_summary">
    <div class="container">
      <div class="pre_title">
        <h1 class="f_fm">MY PAGE</h1>
      </div>
      <div class="pre_caption">
        <div>過去に借りたアイテム</div>
        <div>あなたが過去に借りたアイテムの確認ができます。</div>
      </div>


      <% if @subscription.present? %>
      <div class="accout_status <%= @subscription.plan.name.downcase %>">
        <div class="label">YOUR PLAN IS</div>
        <div class="thestatus f_fm"><%= @subscription.plan.name %></div>
        <div class="status_icon"><span></span></div>
        <div class="">
          <% if @user.bill_address.present? %>
          <%= @user.bill_address.lastname %> <%= @user.bill_address.firstname %>
          <% end %>
          様の</div>
        <div class=""><%= link_to "登録情報", user_setting_path %></div>
      </div>
      <% end %>

      <div class="wrap_index">
        <div class="index_filter">
          <div class="">
            <h3><%= link_to "あなたのお気に入りアイテム", account_path %></h3>
          </div>
          <% if @orders.present? %>
              <h3><%= link_to "購入したアイテム", user_orders_path %></h3>
          <% end %>
        </div>
        <div class="index_products">
          <h3 class="pre_main_col">あなたが過去にレンタルしたアイテム</h3>

          <div class="panel rentaled_item_list">
            <ul class="ul">
              <% @rental_items.each do |rental_item| %>
                <li>
                  <div class="image_col">
                    <%= link_to product_image(rental_item.variant.product), product_path(rental_item.variant.product) %>
                  </div>
                  <div class="info_col">
                    <div class="">ブランド名：
                      <% if rental_item.variant.product.brands.present? %>
                          <%= rental_item.variant.product.brands.first.name %>
                      <% end %>
                     </div>
                    <div class="">お気に入り登録数：<%= rental_item.variant.product.total_favorite %>人</div>
                    <div class="">価格：<%= display_price(rental_item.variant.product) %></div>
                    <div class="">累計ビュー：<%= rental_item.variant.product.impressions_count %>pv</div>
                  </div>
                  <div class="button_col">
                    <% if rental_item.state == "ready" %>
                        <input type="button" name="name" value="配送準備中" class="rent_now">
                    <% elsif rental_item.state == "shipped" %>
                        <input type="button" name="name" value="レンタル中" class="rent_now">
                    <% elsif rental_item.state == "returned" %>
                        <input type="button" name="name" value="返却済み" class="rent_now">
                    <% elsif rental_item.state == "purchased" %>
                        <input type="button" name="name" value="購入済み" class="rent_now">
                    <% end %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/spree/users/setting.html.erb
<% content_for :title, head_title("会員登録情報 | 月額制メンズファッションレンタルKASHI KARI") %>
<% content_for :meta, meta_tags("会員登録情報,レンタル,メンズファッション,ブランド,コーディネート,着こなし,KASHI KARI",
                                "会員登録情報です。| KASHI KARIはメンズファッションアイテムが月額1980円から借り放題になるレンタルサービスです。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。") %>


<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><%= link_to 'メンズファッションレンタル KASHI KARI TOP', root_path %></li>
      <li><%= link_to "マイページ", account_path %></li>
      <li>会員登録情報</li>
    </ul>
  </div>
</nav>
<section id="users" class="users-edit">

  <div class="container">

    <div class="pre_title pre_hero">
      <h1 class="f_fm">EDITING USER<%#= accurate_title %></h1>
    </div>

    <section data-hook="account_summary" class="account_summary">

      <% if @subscription.present? %>
          <div class="accout_status <%= @subscription.plan.name.downcase %>">
            <div class="label">YOUR PLAN IS</div>
            <div class="thestatus f_fm"><%= @subscription.plan.name %></div>
            <div class="status_icon"><span></span></div>
            <div class="">
              <% if @user.bill_address.present? %>
                  <%= @user.bill_address.lastname %> <%= @user.bill_address.firstname %>
              <% end %>
              様の
            </div>
            <div class=""><%= link_to "登録情報", user_setting_path %></div>
          </div>
      <% end %>

      <div class="summary_head">
        <h2>会員登録情報</h2>
      </div>
      <div class="summary_table">
        <div class="summary_row">
          <div class="label">配送情報</div>
          <div class="naiyou">
            <% if @user.ship_address.present? %>
             <%= @user.ship_address.zipcode %><br>
             <%= @user.ship_address.city %><br>
             <%= @user.ship_address.address1 %><%= @user.ship_address.address2 %><br>
             <%= @user.ship_address.phone %><br>

            <% end %>
            </div>
          <div class="button_right">
            <%= link_to Spree.t(:edit), user_edit_address_path, :class => 'button edit' %>
          </div>
        </div>
        <div class="summary_row">
          <div class="label"><%= Spree.t(:email) %></div>
          <div class="naiyou"><%= @user.email %></div>
          <div class="button_right">
            <%= link_to Spree.t(:edit), spree.edit_account_path, :class => 'button' %>
          </div>
        </div>
        <div class="summary_row">
          <div class="label">取引履歴</div>
          <div class="naiyou"></div>
          <div class="button_right">
            <%= link_to "閲覧", user_billing_path, :class => 'button edit' %>
          </div>
        </div>
        <div class="summary_row">
          <div class="label">退会</div>
          <div class="naiyou"></div>
          <div class="button_right">
            <%= link_to "退会", user_unsubscribe_path, :class => 'button edit' %>
          </div>
        </div>
      </div>
      <div class="backToMypage">
        <%= link_to "マイページに戻る", account_path, :class => 'button' %>
      </div>
    </section>
  </div>
</section>