config/routes.rb
Rails.application.routes.draw do

  Spree::Core::Engine.routes.draw do

    namespace :api, defaults: { format: 'json' } do
      resources :rental_items, only: [:update]
    end

    namespace :admin do
      get '/csv_imports', controller: :csv_imports, action: :index, as: :csv_import_index
      post '/csv_imports/template', controller: :csv_imports, action: :template, as: :csv_import_template, defaults: { format: 'csv' }
      post '/csv_imports/import', controller: :csv_imports, action: :import, as: :csv_import_import, defaults: { format: 'html' }

      resources :recurrings, except: :show do
        resources :plans, except: :show
      end

      resources :rental_items do
        member do
          put :ship
          put :return
          put :purchase
          get :export
        end
      end

      resources :taxons_descriptions, except: :show

      resources :subscriptions, only: :index
      resources :subscription_events, only: :index
    end

    resources :recurring_hooks, only: :none do
      post :handler, on: :collection
    end

    resources :subscriptions, only: [:index, :create, :destroy, :new]

    get '/subscriptions/step1' => 'subscriptions#step1', :as => :subscriptions_step1
    get '/subscriptions/step2' => 'subscriptions#step2', :as => :subscriptions_step2
    get '/subscriptions/registration' => 'subscriptions#registration', :as => :subscriptions_registration
    put '/subscriptions/registration' => 'subscriptions#update_registration', :as => :update_subscriptions_registration

    resources :rental_items

    post 'rental_items/cancel' => 'rental_items#cancel', :as => :rental_item_cancel

    #Filter Products
    #get '/products' => 'products#index'
    #get '/products/:name' => 'products#index'
    #get '/products/:brand_name/:item_name' => 'products#index'


    get 'brands' => 'brands#index', :as => :brands
    #get 'brands/:id' => 'brands#show', :as => :brand
    get 'brands/:id' => 'products#index', :as => :brand
    get 'brands/:brand_name/:item_name' => 'products#index'
    get 'brands/:id/*sub_id' => 'brands#show_with_category', :as => :brand_with_category
    #get 'category/:id' => 'category#show', :as => :category
    get 'category/:id' => 'products#index', :as => :category
    put 'users/add_to_favorite/:variant_id' => 'users#add_to_favorite', :as => :add_to_favorite_user

    # thanks
    get '/thankyou' => 'users#thankyou', :as => :thankyou
    get '/thanks_silver' => 'users#thanks_silver', :as => :thanks_silver
    get '/thanks_gold' => 'users#thanks_gold', :as => :thanks_gold
    get '/thanks_black' => 'users#thanks_black', :as => :thanks_black

    get 'account/billing' => 'users#billing', :as => :user_billing
    get 'account/history' => 'users#history', :as => :user_history
    get 'account/orders' => 'users#orders', :as => :user_orders
    get 'account/favorites' => 'users#favorites', :as => :user_favorites
    get 'account/setting' => 'users#setting', :as => :user_setting
    get 'account/unsubscribe' => 'users#unsubscribe', :as => :user_unsubscribe
    get 'account/edit/address' => 'users#edit_address', :as => :user_edit_address
    patch 'account/update_address' => 'users#update_address', :as => :user_update_address

    #checkout complete path
    get '/checkout/complete' => 'orders#complete', :as => :complete_order

    # pages
    get '/pages/qa' => 'pages#qa', :as => :pages_qa
    get '/pages/policy' => 'pages#policy', :as => :pages_policy
    get '/pages/termofuse' => 'pages#termofuse', :as => :pages_termofuse
    get '/pages/about' => 'pages#about', :as => :pages_about
    get '/pages/asct' => 'pages#asct', :as => :pages_asct
  end

  mount Spree::Core::Engine, :at => '/'

  #Error handling
  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/concerns/spree/plan/api_handler.rb
module Spree
  class Plan < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        #before_validation :set_api_plan_id, on: :create
        #after_create :create_plan
        #after_update :delete_plan, :if => [:deleted_at_changed?, :deleted_at?]
        #after_update :update_plan, :if => :name_changed?
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error: #{e.message}"
          errors.add :base, e.message
          false
        end
      end

      def provider
        recurring.present? ? recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private

      def set_api_plan_id
        #provider.set_api_plan_id(self)
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        extend ActiveSupport::Concern

        included do
          include SubscriptionApiHandler
          include SubscriptionEventApiHandler
        end

        def client
          @client ||= WebPay.new(preferred_secret_key)
        end

        def error_class
          WebPay::ApiError
        end

        def raise_invalid_object_error(object, type)
          raise error_class.new("Not a valid object.") unless object.is_a?(type)
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionApiHandler
          def subscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            customer_id = find_or_create_customer(subscription)

            recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                description: subscription.plan.name,
            )

            if recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            recursion
          end

          def change_subscription(subscription, old_subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)

            if subscription.amount > old_subscription.amount
              upgrade(subscription, old_subscription)
            else
              downgrade(subscription, old_subscription)
            end

          end

          def upgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)
            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            extra_charge = subscription.amount - old_subscription.amount
            client.charge.create(
                amount: extra_charge,
                currency: "jpy",
                customer: customer_id,
                description: "会員プラン変更料 #{old_subscription.plan.name}から#{subscription.plan.name}に変更"
            )

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion

          end

          def downgrade(subscription, old_subscription)
            customer_id = find_or_create_customer(subscription)

            old_recursion = client.recursion.retrieve(old_subscription.gateway_recursion_id)
            if old_recursion.deleted == true
              raise WebPay::ApiError.new("該当の定期課金は既に削除されています。サービス運営会社にお問い合わせください。")
              return
            end

            new_recursion = client.recursion.create(
                amount: subscription.plan.amount,
                currency: "jpy",
                customer: customer_id,
                period: "month",
                first_scheduled: old_recursion.next_scheduled,
                description: subscription.plan.name,
            )


            if new_recursion.status != "active"
              raise WebPay::ApiError.new("カードの決済に失敗しました。入力したカードの番号が合っているか確認してください。")
              return
            end

            new_recursion


          end

          def unsubscribe(subscription)
            raise_invalid_object_error(subscription, Spree::Subscription)
            client.recursion.delete(id: subscription.gateway_recursion_id)
          end

          private

          def find_or_create_customer(subscription)
            if subscription.source.gateway_customer_profile_id.present?
              subscription.source.gateway_customer_profile_id
            else
              customer = client.customer.create(
                  email: subscription.user.email,
                  description: subscription.user.email,
                  card: subscription.source.gateway_payment_profile_id,
              )

              subscription.source.update_attributes!({
                                                         gateway_customer_profile_id: customer.id,
                                                         gateway_payment_profile_id: nil
                                                     })

              customer.id
            end
          end
        end
      end
    end
  end
end

app/models/concerns/spree/recurring/webpay_recurring/api_handler/subscription_event_api_handler.rb
module Spree
  class Recurring < Spree::Base
    class WebpayRecurring < Spree::Recurring
      module ApiHandler
        module SubscriptionEventApiHandler
          def retrieve_event(event_id)
            begin
              client.event.retrieve(event_id)
            rescue error_class => e
              logger.error "Webpay Event error: #{e.message}"
              errors.add :base, "Webpay Event error: #{e.message}"
              nil
            end
          end

          def client
             @client ||= WebPay.new(preferred_secret_key)
          end
        end
      end
    end
  end
end

app/models/concerns/spree/subscription/api_handler.rb
module Spree
  class Subscription < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        attr_accessor :card_token
        before_create :subscribe
        before_update :unsubscribe, :if => [:unsubscribed_at_changed?, :unsubscribed_at?]
      end

      def subscribe
          if user.subscriptions.undeleted.any?
              old_subscription = user.subscriptions.undeleted.first

              # subscribe new recursion
              recursion = provider.change_subscription(self, old_subscription)

              # unsubscribe recursion and delete subscription
              old_subscription.save_and_manage_api(unsubscribed_at: Time.current)
          else
            # subscribe new recursion
            recursion = provider.subscribe(self)
          end

          self.gateway_recursion_id = recursion.id
          self.subscribed_at = Time.current
      end

      def unsubscribe
        provider.unsubscribe(self)
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error while subscribing: #{e.message}"
          errors.add :base, "There was a problem with your credit card"
          false
        end
      end

      def provider
        plan.try(:recurring).present? ? plan.recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private
    end
  end
end

app/models/concerns/spree/subscription/role_subscriber.rb
module Spree
  class Subscription < ActiveRecord::Base
    module RoleSubscriber
      extend ActiveSupport::Concern

      included do
        before_create :add_role_subscriber, :unless => :unsubscribed_at?
        before_update :remove_role_subscriber, :if => :unsubscribed_at?
      end

      def add_role_subscriber
        if role = subscriber_role
          user.spree_roles << role
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      # TODO don't remove role subscriber when upgrade/downgrade
      def remove_role_subscriber
        if role = subscriber_role
          user.spree_roles.destroy(role)
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      private

      def subscriber_role
        Spree::Role.where(name: 'subscriber').first
      end
    end
  end
end

app/models/spree/ability.rb
# Implementation class for Cancan gem.  Instead of overriding this class, consider adding new permissions
# using the special +register_ability+ method which allows extensions to add their own abilities.
#
# See http://github.com/ryanb/cancan for more details on cancan.
require 'cancan'
module Spree
  class Ability
    include CanCan::Ability

    class_attribute :abilities
    self.abilities = Set.new

    # Allows us to go beyond the standard cancan initialize method which makes it difficult for engines to
    # modify the default +Ability+ of an application.  The +ability+ argument must be a class that includes
    # the +CanCan::Ability+ module.  The registered ability should behave properly as a stand-alone class
    # and therefore should be easy to test in isolation.
    def self.register_ability(ability)
      self.abilities.add(ability)
    end

    def self.remove_ability(ability)
      self.abilities.delete(ability)
    end

    def initialize(user)
      self.clear_aliased_actions

      # override cancan default aliasing (we don't want to differentiate between read and index)
      alias_action :delete, to: :destroy
      alias_action :edit, to: :update
      alias_action :new, to: :create
      alias_action :new_action, to: :create
      alias_action :show, to: :read
      alias_action :index, :read, to: :display


      user ||= Spree.user_class.new

      if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
        can :manage, :all
      else
        can :display, Country
        can :display, OptionType
        can :display, OptionValue
        can :create, Order
        can [:read, :update], Order do |order, token|
          order.user == user || order.guest_token && token == order.guest_token
        end
        can :display, CreditCard, user_id: user.id
        can :display, Product
        can :display, ProductProperty
        can :display, Property
        can :create, Spree.user_class
        can [:read, :update, :destroy, :thankyou, :add_to_favorite], Spree.user_class, id: user.id
        can :display, State
        can :display, Taxon
        can :display, Taxonomy
        can :display, Variant
        can :display, Zone
      end

      # Include any abilities registered by extensions, etc.
      Ability.abilities.each do |clazz|
        ability = clazz.send(:new, user)
        @rules = rules + ability.send(:rules)
      end
    end
  end
end

app/models/spree/credit_card_decorator.rb
Spree::CreditCard.class_eval do
  belongs_to :recurring, :class_name => 'Spree::Recurring'
  has_many :subscriptions, as: :source
end

app/models/spree/favorite.rb
module Spree
  class Favorite < ActiveRecord::Base
    belongs_to :user
    belongs_to :variant, :counter_cache => :favorites_count

    def variant
      Spree::Variant.unscoped { super }
    end

    def user
      Spree::User.unscoped { super }
    end

  end
end

app/models/spree/image_decorator.rb
module Spree
  Image.class_eval do
    #before_validation :parse_attachment_from_source
    attr_accessor :source

    attachment_definitions[:attachment][:styles] = {
        :mini => '80x80>', # thumbs under image
        :small => '160x160>', # images on category view
        :thumb => '240x240>', # images on category view
        :product => '400x400>', # full product image
        :large => '600x600>' # light box image
    }

    attachment_definitions[:attachment][:path] = Kashikari::Application.config.image_path
    attachment_definitions[:attachment][:default_url] = Kashikari::Application.config.default_url

    Spree::Image.attachment_definitions[:attachment][:convert_options] = { all: Kashikari::Application.config.paperclip_options }


    def parse_attachment_from_source
      if source.present?
        self.attachment = URI.parse(source)
      end
    end

  end
end

app/models/spree/payment_method/check_decorator.rb
module Spree
  PaymentMethod::Check.class_eval do
    def payment_profiles_supported?
      true
    end
  end
end

app/models/spree/plan_product.rb
module Spree
  class PlanProduct < ActiveRecord::Base
    belongs_to :plan
    belongs_to :product
  end
end

app/models/spree/plan_taxon.rb
module Spree
  class PlanTaxon < ActiveRecord::Base
    belongs_to :plan
    belongs_to :taxon
  end
end

app/views/spree/category/_p_filter.html.erb
<nav>
  <div class="">
    <h3><%= link_to "全ての商品", products_path %></h3>
  </div>
  <div class="">
    <h3>プラン</h3>
    <ul class="ul">
      <li <%= "class=selected" if params[:plan_id] == Spree::Plan::NAME[:black].to_s %>>
        <%= link_to "BLACK", params.merge({:plan_id => Spree::Plan::NAME[:black]}) %>
      </li>
      <li  <%= "class=selected" if params[:plan_id] == Spree::Plan::NAME[:gold].to_s %>>
        <%= link_to "GOLD", params.merge({:plan_id => Spree::Plan::NAME[:gold]}) %>
      </li>
      <li  <%= "class=selected" if params[:plan_id] == Spree::Plan::NAME[:silver].to_s %>>
        <%= link_to "SILVER", params.merge({:plan_id => Spree::Plan::NAME[:silver]}) %>
      </li>
      <li  <%= "class=selected" if params[:plan_id] == Spree::Plan::NAME[:bronze].to_s %>>
        <%= link_to "BRONZE", params.merge({:plan_id => Spree::Plan::NAME[:bronze]}) %>
      </li>
    </ul>
  </div>

  <div class="filter_brand">
    <h3>ブランド</h3>
    <ul class="ul">
      <% @brands.first.root.children.map.each do |taxon| %>
          <li>
            <%= link_to taxon.name, brand_with_category_path(params.merge({:id => taxon.permalink, :sub_id => params[:id]})) %>
          </li>
      <% end %>
    </ul>
    <div class="acrd_box">
      <span class="brand_accordion">ブランドを選択する</span>
    </div>
  </div>

  <div class="">
    <h3>アイテム</h3>
    <ul class="ul">
      <% @categories.first.root.children.map.each do |taxon| %>
          <li <%= "class=selected" if params[:id] == taxon.permalink %>>
            <%= link_to taxon.name, category_path(params.merge({:id => taxon.permalink})) %>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="">
    <h3>素材</h3>
    <ul class="ul">
      <% @materials.first.root.children.map.each do |taxon| %>
          <li  <%= "class=selected" if params[:material_id] == taxon.id.to_s %>>
            <%= link_to taxon.name, params.merge({:material_id => taxon.id}) %>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="">
    <h3>柄</h3>
    <ul class="ul">
      <% @designs.first.root.children.map.each do |taxon| %>
          <li <%= "class=selected" if params[:design_id] == taxon.id.to_s %>>
            <%= link_to taxon.name, params.merge({:design_id => taxon.id}) %>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="">
    <h3>色</h3>
    <ul class="ul">
      <% @colors.first.root.children.map.each do |taxon| %>
          <li <%= "class=selected" if params[:color_id] == taxon.id.to_s %>>
            <%= link_to taxon.name, params.merge({:color_id => taxon.id}) %>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="">
    <h3>サイズ</h3>
    <ul class="ul">
      <% @sizes.first.root.children.map.each do |taxon| %>
          <li <%= "class=selected" if params[:size_id] == taxon.id.to_s %>>
            <%= link_to taxon.name, params.merge({:size_id => taxon.id}) %>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="">
    <h3>ソート</h3>
    <ul class="ul">
      <li <%= "class=selected" if params[:order] == "desc_by_created_at" %>>
        <%= link_to '新着順', params.merge({:order => "desc_by_created_at"}) %>
      </li>
      <li <%= "class=selected" if params[:order] == "desc_by_favorite" %>>
        <%= link_to 'お気に入りが多い順', params.merge({:order => "desc_by_favorite"}) %>
      </li>
    </ul>
  </div>
</nav>

app/views/spree/category/show.html.erb
<% content_for :title, head_title("#{@taxon.name} | ブランドネクタイ通販・レンタル KASHI KARI").html_safe %>
<% content_for :meta, meta_tags("#{@taxon.name},レンタル,メンズファッション,ブランド,通販,コーディネート,着こなし,KASHI KARI".html_safe,
                                "#{@taxon.name}の商品一覧です。| KASHI KARIは#{@taxon.name}ブランドネクタイを通販やレンタル出来るKASHI KARI。通販よりお得に#{@taxon.name}を楽しめます。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。".html_safe) %>


<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><a href="#">メンズファッションレンタル KASHI KARI TOP</a></li>
      <li><%= link_to "メンズファッション一覧", products_path %></li>
      <li><%= @taxon.name %></li>
    </ul>
  </div>
</nav>
<div class="products">
  <div class="container">
    <div class="wrap_index">
      <section class="index_filter">
        <%= render :partial => 'p_filter' %>
      </section>
      <section class="index_products">
        <section class="products_result">
          <span><%= page_entries_info(@products) %></span>
        </section>
        <section class="products_pager">
          <%= paginate @products %>
        </section>
        <section class="products_cont">
          <ul class="ul">
            <% @products.each do |product| %>
                <% if product.plans.present? %>
                    <% if product.plans.pluck(:name).include?("BRONZE") %>
                        <% plan = "bronze" %>
                    <% elsif product.plans.pluck(:name).include?("SILVER") %>
                        <% plan = "silver" %>
                    <% elsif product.plans.pluck(:name).include?("GOLD") %>
                        <% plan = "gold" %>
                    <% elsif product.plans.pluck(:name).include?("BLACK") %>
                        <% plan = "black" %>
                    <% end %>
                <% end %>
                <li class="<%= plan if plan.present? %>
              <% if product.total_on_hand < 1 %> outOfStock
              <% elsif product.total_on_hand <= product.master.rental_qty %> duringTheRental
              <% end %>">
                  <%= link_to product_path(product) do %>
                      <%= original_image(product) %>
                      <%= image_tag "sp/common/fan/dot_#{plan}.gif", :class => 'plan_dot' %>
                      <% if product.total_on_hand < 1 %>
                          <div class="">
                            <span>販売済み</span>
                          </div>
                      <% elsif product.total_on_hand <= product.master.rental_qty %>
                          <div class="">
                            <span>レンタル中</span>
                          </div>
                      <% end %>
                  <% end  %>
                  <h3 class="f_fm">
                    <% if product.brands.present? %>
                        <%= product.brands.first.name %>
                    <% end %>
                  </h3>
                  <% if spree_current_user %>
                      <% if spree_current_user.liked?(product.master) %>
                          <%= link_to "追加しました!", add_to_favorite_user_path(product.master), class: 'vote liked', method: :put, remote: true, data: {toggle_text: 'お気に入りに追加', toggle_href: add_to_favorite_user_path(product.master), id: product.master.id} %>
                      <% else %>
                          <%= link_to "お気に入りに追加", add_to_favorite_user_path(product.master), class: 'vote', method: :put, remote: true, data: {toggle_text: '追加しました!', toggle_href: add_to_favorite_user_path(product.master), id: product.master.id} %>
                      <% end %>
                  <% else %>
                      <%= link_to "お気に入りに追加", signup_path, :class => "signin_pc", :id => product.master.id %>
                  <% end %>
                </li>

            <% end %>
          </ul>
        </section>
        <section class="products_pager">
          <%= paginate @products %>
        </section>
      </section>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(".signin_pc").click(function(){
    sessionStorage.setItem('product_id', $(this).attr('id'));
  });
</script>

app/views/spree/category/show_smart_phone.html.erb
<% content_for :title, head_title("#{@taxon.name} | ブランドネクタイ通販・レンタル KASHI KARI").html_safe %>
<% content_for :meta, meta_tags("#{@taxon.name},レンタル,メンズファッション,ブランド,通販,コーディネート,着こなし,KASHI KARI".html_safe,
                                "#{@taxon.name}の商品一覧です。| KASHI KARIは#{@taxon.name}ブランドネクタイを通販やレンタル出来るKASHI KARI。通販よりお得に#{@taxon.name}を楽しめます。送料無料＆返却期限なしでコーディネート/着こなしを楽しもう。".html_safe) %>

<% content_for :brand_filter do %>
    <% @brands.first.root.children.map.each do |taxon| %>
        <li>
          <%= link_to taxon.name, brand_with_category_path(params.merge({:id => taxon.permalink, :sub_id => params[:id]})) %>
        </li>
    <% end %>
<% end %>
<% content_for :category_filter do %>
    <% @categories.first.root.children.map.each do |taxon| %>
        <li <%= "class=selected" if params[:id] == taxon.permalink %>>
          <%= link_to taxon.name, category_path(params.merge({:id => taxon.permalink})) %>
        </li>
    <% end %>
<% end %>

<nav class="breadcrumbs">
  <div class="container">
    <ul class="ul">
      <li><%= link_to 'メンズファッションレンタル KASHI KARI TOP', root_path %></li>
      <li><%= link_to "メンズファッション一覧", products_path %></li>
      <li><%= @taxon.name %></li>
    </ul>
  </div>
</nav>
<div class="products">
  <div class="container">
    <section class="products_head">
      <h1><%= @taxon.name %>　<span><%= page_entries_info(@products) %></span></h1>
    </section>
    <section class="sort">
      <form>
        <select onChange="location.href=this.options[this.selectedIndex].value" >
          <option>選択してください</option>
          <option value="<%= url_for(params.merge({:order => "desc_by_created_at"})) %>" <%= "selected" if params[:order] == "desc_by_created_at" %>>新着順</option>
          <option value="<%= url_for(params.merge({:order => "desc_by_favorite"})) %>" <%= "selected" if params[:order] == "desc_by_favorite" %>>お気に入りが多い順</option>
        </select>
      </form>
    </section>
    <section class="products_pager">
      <%= paginate @products %>
    </section>
    <section class="products_cont">
      <ul class="ul">
        <% @products.each do |product| %>
            <% if product.plans.present? %>
                <% if product.plans.pluck(:name).include?("BRONZE") %>
                    <% plan = "bronze" %>
                <% elsif product.plans.pluck(:name).include?("SILVER") %>
                    <% plan = "silver" %>
                <% elsif product.plans.pluck(:name).include?("GOLD") %>
                    <% plan = "gold" %>
                <% elsif product.plans.pluck(:name).include?("BLACK") %>
                    <% plan = "black" %>
                <% end %>
            <% end %>

            <li class="<%= plan if plan.present? %>
              <% if product.total_on_hand < 1 %> outOfStock
              <% elsif product.total_on_hand <= product.master.rental_qty %>duringTheRental
              <% end %>">
              <div class="li_inner">
                <h3 class="f_fm">
                  <% if product.brands.present? %>
                      <%= product.brands.first.name %>
                  <% end %>
                </h3>

                <div class="image_wrap">
                  <%= link_to original_image(product), product_path(product) %>
                  <% if product.total_on_hand < 1 %>
                      <div class="">
                        <span>販売済み</span>
                      </div>
                  <% elsif product.total_on_hand <= product.master.rental_qty %>
                      <div class="">
                        <span>レンタル中</span>
                      </div>
                  <% end %>
                </div>
                <div class="fab_btn">
                  <div class="fabbutton">
                    <% if spree_current_user %>
                        <% if spree_current_user.liked?(product.master) %>
                            <%= link_to product.total_favorite, add_to_favorite_user_path(product.master), class: 'vote liked', method: :put, remote: true, data: {toggle_text: product.total_favorite, toggle_href: add_to_favorite_user_path(product.master), id: product.master.id} %>
                        <% else %>
                            <%= link_to product.total_favorite, add_to_favorite_user_path(product.master), class: 'vote', method: :put, remote: true, data: {toggle_text: product.total_favorite, toggle_href: add_to_favorite_user_path(product.master), id: product.master.id} %>
                        <% end %>
                    <% else %>
                        <%= link_to product.total_favorite, signup_path, :class => "signin_mobile", :id => product.master.id %>
                    <% end %>

                    </div>
                </div>
              </div>
            </li>

        <% end %>
      </ul>
    </section>
    <section class="products_pager pager_bottom">
      <%= paginate @products %>
    </section>
  </div>
</div>
<script type="text/javascript">
  $(".signin_mobile").click(function(){
    sessionStorage.setItem('product_id', $(this).attr('id'));
  });
</script>